config/routes.rb
Rails.application.routes.draw do
  root to: 'players#index'
  get 'players/by_name' => 'players#by_name'
  get 'players/:id/matches_played' => 'players#matches_played'
  resources 'players'
  get 'matches/recent' => 'matches#recent'
  resources 'matches'
end

app/models/match.rb
class Match < ActiveRecord::Base


  include ActiveModel::Validations  #needed to define a custom validator



	belongs_to :winner, :class_name => 'Player', :foreign_key => 'winner_id'
  belongs_to :loser, :class_name => 'Player', :foreign_key => 'loser_id'

  validates_associated :winner, :loser
  validates :winner_score, numericality: {greater_than_or_equal_to: 0, 
                                          less_than_or_equal_to: 9}  
  validates :loser_score, numericality: {greater_than_or_equal_to: 0, 
                                          less_than_or_equal_to: 9}

  validates :date, :winner_id, :loser_id, presence: true                                        

  
  # Swaps the ranks of a match's players if the lower ranked player won
  # Uses the associations defined for match to access winner and loser
  def adjust_players
    print "winner rank is #{winner.rank}, loser_rank is #{loser.rank}"
    if winner.rank > loser.rank
      temp = winner.rank
      winner.update(rank: loser.rank)
      loser.update(rank: temp)
    end
  end

  class MyValidator < ActiveModel::Validator
    def validate(match)
      if match.winner_id == match.loser_id
        match.errors[:players] << "No playing with yourself please!"
      end
      if match.winner_score < match.loser_score
        match.errors[:loser] << "Winner score must be higher"
      end
    end
  end

  validates_with MyValidator




end

app/models/player.rb
class Player < ActiveRecord::Base

  def matches
    Match.where("winner_id = ? OR loser_id = ?", id, id)
  end

  def self.active_players
    Player.where("hidden = ? AND deleted = ?", false, false)
  end

  def self.active_players_by_rank
    active_players.order(rank: :asc)
  end

  def self.active_players_by_name
    active_players.order(name: :asc)
  end

  def self.inactive_players_by_name
    Player.where("hidden = ? and deleted = ?", true, false).order(name: :asc)
  end

  def hidden?
    hidden == true
  end

  def deleted?
    deleted == true
  end

  def active?
    !hidden? and !deleted?
  end

  def inactive?
    hidden? or deleted?
  end

  def self.name_selection
    player_list = Array.new
    Player.select(:name) { |p| player_list << [ p.name, p.id ] }
    player_list
  end

  def self.move_players_down(starting_rank)
    Player.where("rank >= ?", starting_rank).update_all("rank = rank + 1")
  end

  def self.move_players_up(starting_rank)
    Player.where("rank >= ?", starting_rank).update_all("rank = rank - 1")
  end

	def insert
    #How many ranked players already?
		number_of_players = Player.active_players.count

    if inactive?
      # No need to adjust rankings
      self.rank = 999
    elsif rank == 0 or rank.nil? or rank > number_of_players 
      # If the requested rank is out of bounds, set to lowest rank
      self.rank = number_of_players + 1
    else
      # Otherwise, move players down to make room for insertion
      Player.move_players_down(rank)
    end

    # Now insert player at desired rank
    save
  end

  def hide
    # If they are currently ranked, move them up
    if active?
      Player.move_players_up(rank + 1)
    end
    self.hidden = true
    self.rank = 999
  end

  def delete
    if active?
      Player.move_players(rank+1)
    end
    self.deleted = true
    self.rank = 999
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def recent
    @matches = Match.order(date: :desc)
  end

  def index
    @matches = Match.active_players_by_rank
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to matches_recent_path, notice: 'Match was recorded'
      @match.adjust_players
    else
      @match.errors.messages do |message| 
        flash[:notice] << message
      end
        render :new
    end
  end


  private

  def match_params
    params.require(:match).permit(:date, :winner_id, :loser_id, 
                                  :winner_score, :loser_score)
  end

end 

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		@players = Player.where(hidden: false, deleted: false).order(rank: :asc)
	end

  def by_name
    @active_players = Player.active_players_by_name
    @inactive_players = Player.inactive_players_by_name
  end

	def new
		@player = Player.new
	end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @now_hidden = !@player.hidden and params[:hidden]
    @now_unhidden = @player.hidden and !params[:hidden]
    @success = @player.update_attributes(player_params)
    if @success 
      if @now_hidden
        @player.hide
      elsif
        @now_unhidden
        @player.unhide
      end
      redirect_to players_path, notice: 'Player was updated successfully'
    else
      render :edit
    end
  end

  def matches_played
    @player = Player.find(params[:id])
    @matches = @player.matches
  end

	def create
		@player = Player.new(player_params)
    if @player.insert
      redirect_to players_path, notice: 'Player was added'
    else
      render :new
    end
  end
end


private
  # Never trust parameters from the scary internet, only allow white list
  def player_params
    params.require(:player).permit(:name, :email, :phone, :rank, :joined, :hidden, :deleted)
  end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'BHTC Rankings', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
	    aria-haspopup="true" aria-expanded="false">Matches <span
	class="caret"></span></a>
	<ul class="dropdown-menu">
	  <li><%= link_to "Recent Matches", matches_recent_path %></li>
	  <li><a href="#">All Matches</a></li>
	  <li><%= link_to "Record a Match", new_match_path %></li>
	  <li role="separator" class="divider"></li>
	  <li><a href="#">Separated link</a></li>
	  <li role="separator" class="divider"></li>
	  <li><a href="#">One more separated link</a></li>
	</ul>
</li>
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
	    aria-haspopup="true" aria-expanded="false">Players <span
	class="caret"></span></a>
	<ul class="dropdown-menu">
	  <li><%= link_to 'List Players by Rank', players_path %></li>
	  <li><%= link_to 'List Players by Name', players_by_name_path %></li>
	  <li><a href="#">List Inactive Players</a></li>
	  <li role="separator" class="divider"></li>
	  <li><%= link_to 'New Player', new_player_path %></li>
	  <li><%= link_to 'Edit Player', '#' %></li>
	</ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rankings" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rankings" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/matches/new.html.erb
<div class="container">
  <h1>Record a Match</h1>
	<%= form_for(@match) do |m| %>
<%#   <%= render 'shared/error_messages' %>
    <form role="form">
      <fieldset>
        <legend>Players</legend>
        <div class="row">
          <div class="form-group col-sm-4">
            <%= m.label :winner_id, class: "control-label" %><br>
            <%= m.select :winner_id,  options_from_collection_for_select(Player.order(name: :asc), :id, :name), {prompt: "Select winner"}, { class: "form-control" } %>
          </div>
          <div class="form-group col-sm-4">
            <%= m.label :loser_id, class: "control-label"  %><br>
            <%= m.select :loser_id,  options_from_collection_for_select(Player.order(name: :asc), :id, :name), {prompt: "Select loser"}, { class: "form-control" } %>
          </div>
        <row>
      </fieldset>

      <fieldset>
        <legend>Match Result</legend>
        <div class="row">
          <div class="form-group col-sm-4">
            <%= m.label :date, class: "control-label" %><br>
            <%= m.date_field :date, value: Time.now, class: "form-control", 
                      autofocus: true %>
          </div>

          <div class="form-group col-sm-4">
            <%= m.label :winner_score, "Winner Score", class: "control-label"  %><br>
            <%= m.text_field :winner_score, class: "form-control" %>
          </div>
          <div class="form-group col-sm-4">
            <%= m.label :loser_score, "Loser Score", class: "control-label"  %><br>
            <%= m.text_field :loser_score, class: "form-control" %>
          </div>
        </div>
        <div class="actions">
          <%= m.submit "Record Match", class: "btn btn-primary" %>
        </div>
      <fieldset>
    </form>
  <% end %>
</div>

app/views/matches/recent.html.erb
 

<body>
  <h3>Recent Matches</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Winner</th>
        <th>Loser</th>
        <th>Score</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @matches.each do |m| %>
        <tr>
          <td>
            <%= m.date.strftime("%A, %x") %> 
          </td>
          <td><%= m.winner.name %></td>
          <td><%= m.loser.name %></td>
          <td><%= "#{m.winner_score}/#{m.loser_score}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/players/_player.html.erb
	<%= form_for(player) do |p| %>
<%#   <%= render 'shared/error_messages' %>
    <form role="form">
      <div class="form-group">
        <%= p.label :name %><br>
        <%= p.text_field :name, class: "form-control", size: 40, autofocus: true,
                                    placeholder: "e.g John Doe" %>
      </div>
      <div class="form-group">
        <%= p.label :email %><br>
        <%= p.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= p.label :phone %><br>
        <%= p.text_field :phone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= p.label :rank, "Initial rank" %><br>
        <%= p.number_field :rank, class: "form-control" %>
        <span class="help-block">
          If the rank isn't on the ladder (e.g. 999) the player will be added to the bottom
        </span> 
      </div>
      <div class="form-group">
        <%= p.label :joined, "Date joined" %><br>
        <%= p.date_field :joined, class: "form-control", value: Time.now %>
      </div>
      <div class="form-group">
        <%= p.label :hidden, "Inactive" %>
        <%= p.check_box :hidden %>
        <span class="help-block">
          Inactive players are excluded from the rankings. 
          Edit their profile to make them active and set their rank.
        </span> 
      </div>
      <div class="actions">
        <%= p.submit "Add Player", class: "btn btn-primary" %>
      </div>
    </form>
  <% end %>

app/views/players/by_name.html.erb
<body>
  <h3>Active Players</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Rank</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @active_players.each do |p| %>
        <tr>
          <td><%= p.name %></td>
          <td><%= p.email %></td>
          <td><%= p.phone %></td>
          <td><%= p.rank %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h3>Inactive Players</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Rank</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @inactive_players.each do |p| %>
        <tr>
          <td><%= p.name %></td>
          <td><%= p.email %></td>
          <td><%= p.phone %></td>
          <td>Unranked</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

app/views/players/edit.html.erb
<div>
  <h1>Edit <%= @player.name %> Profile</h1>
	<%= render @player %>
</div>

app/views/players/index.html.erb
<body>
  <script>
    $(document).ready(function() {
      $('#example tr').click(function(event) {
        window.document.location = $(this).data("pref");
      });
    });
  </script>

<!--   <div class="jumbotron">
    <div class="container">
      <h2>Welcome to Burleigh Tennis Club Ladder!</h2>
      <p>
        If you'd like to join our competition,
        players of all abilities are welcome.
      </p>
      <p><a class="btn btn-primary btn-lg" role="button">
        Learn more &raquo;
      </a><p>
    </div>
  </div> -->
  <div class="container">
  <h3>Rankings</h3>
  <table class="table table-hover" id="example">
    <thead>
      <tr>
        <th>Rank</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @players.each do |p| %>
        <tr data-pref="<%= edit_player_path(p.id) %>">
          <td><%= p.rank %></td>
          <td><%= p.name %></td>
          <td><%= p.email %></td>
          <td><%= p.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</body>

app/views/players/matches_played.html.erb
 <body>
  <h3><%= "#{@player.name} Matches" %></h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Result</th>
        <th>Opponent</th>
        <th>Score</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @matches.each do |m| %>
        <% if @player.id == m.winner_id %>
        <%   won = true %>
        <% end %>

        <% if won %>
          <tr class="success">
        <% else %>
          <tr class="danger">
        <% end %>

          <td><%= m.date.strftime("%A, %x") %> </td>
    
          <% if won %>
            <td>Defeated</td>
            <td><%= m.loser.name %></td>
          <% else %>
            <td>Lost to</td>
            <td><%= m.winner.name %></td>
          <% end %>

          <td><%= "#{m.winner_score}/#{m.loser_score}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

app/views/players/new.html.erb
<div>
  <h1>Add Player</h1>
  <%= render @player %>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>